### ISSUE TITLE
🛑 Site 11 is down

### ISSUE THREAD

**Issue by ahmcosta** [G6Tech/upptime-cc#1]
In [`7400e40`](https://github.com/G6Tech/upptime-cc/commit/7400e40c385244b50526a15f66d39c92b06a09d2
), Site 11 (http://34.203.249.24/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by ralphg6** [comment]
Muito top!

**Comment by ahmcosta** [comment]
Serviço reestabelecido.
